{% set name = "openff-interchange" %}
{% set version = "0.4.0" %}
{% set python_min = python_min|default("0.1a0") %}  # due to a bug in conda-build

package:
  name: openff-interchange-split
  version: {{ version }}

source:
  path: ./build_base.sh
  url: https://github.com/openforcefield/openff-interchange/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 56584ce93d3dd4e695b6e4f99d619e754ac2293547d34a373ec069f9950ff2ab

build:
  number: 1

outputs:
  - name: openff-interchange-base
    script: build_base.sh
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}.*
        - pip
        - setuptools
        - versioneer
      run:
        - python >={{ python_min }},<3.13.0a0
        - pydantic =2
        - openff-toolkit-base ~=0.16.4
        - openff-units =0.2
        - openff-utilities >=0.1.5
      run_constrained:
        - foyer =1
        - jax >=0.3
        - jaxlib >=0.3
        # https://github.com/openforcefield/openff-interchange/issues/960
        - lammps >=2023.08.02
        - smirnoff-plugins >=2024.07.0

    test:
      imports:
        - openff.interchange

  - name: openff-interchange
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}.*
      run:
        - python >={{ python_min }},<3.13.0a0
        - openmm >=7.6,<9
        - {{ pin_subpackage('openff-interchange-base', exact=True) }}
        - openff-toolkit ~=0.16.4
        - panedr

    test:
      imports:
        - openff.interchange
      files:
        - test_stack_imports.py
      commands:
        - python test_stack_imports.py

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A project (and object) for storing, manipulating, and converting molecular mechanics data.
  dev_url: https://github.com/openforcefield/openff-interchange

extra:
  recipe-maintainers:
    - mattwthompson
    - j-wags
