{% set name = "openff-interchange" %}
{% set version = "0.3.1" %}

package:
  name: openff-interchange-split
  version: {{ version }}

source:
  path: ./build_base.sh
  url: https://github.com/openforcefield/openff-interchange/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f779111fbdc5a128a4f5844bcdc07c6e49e68c49278c4ce0668f27dd423f4bda

build:
  number: 0

outputs:
  - name: openff-interchange-base
    script: build_base.sh
    build:
      noarch: python

    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - python >=3.8
        - pydantic <2.0.0a0
        - openmm >=7.6
        - openff-toolkit-base =>0.12.1
        - openff-units >=0.2
        - openff-utilities >=0.1.5
        - openff-models >=0.0.3
      run_constrained:
        - foyer >=0.11.3
        - jax >=0.3
        - jaxlib >=0.3

    test:
      imports:
        - openff.interchange

  - name: openff-interchange
    build:
      noarch: python

    requirements:
      host:
        - python >=3.8
      run:
        - python >=3.8
        - {{ pin_subpackage('openff-interchange-base', exact=True) }}
        - openff-toolkit =>0.12.1
        - panedr

    test:
      imports:
        - openff.interchange
      files:
        - test_stack_imports.py
      commands:
        - python test_stack_imports.py

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A project (and object) for storing, manipulating, and converting molecular mechanics data.
  dev_url: https://github.com/openforcefield/openff-interchange

extra:
  recipe-maintainers:
    - mattwthompson
    - j-wags
