{% set org = "openforcefield" %}
{% set name = "openff-interchange" %}
{% set version = "0.5.4beta1" %}

package:
  name: openff-interchange-split
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: df3e46edec5312bfa18a2f9516ec7f6993d16ebe9301d1dfeda550a090a3945f

build:
  number: 0

outputs:
  - name: openff-interchange-base
    script: build_base.sh
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        - setuptools_scm
      run:
        - python >={{ python_min }}
        - numpy <2.5
        - pydantic >=2.13
        - openff-toolkit-base >=0.18,<0.19
        - openff-units >=0.4.0beta1
        - openff-utilities >=0.1.5
      run_constrained:
        - foyer =1
        - jax >=0.3
        - jaxlib >=0.3
        # https://github.com/openforcefield/openff-interchange/issues/960
        - lammps >=2023.08.02
        - smirnoff-plugins >=2024.07.0

    test:
      requires:
        - python {{ python_min }}
      imports:
        - openff.interchange

  - name: openff-interchange
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        - setuptools_scm
      run:
        - python >={{ python_min }}
        - openmm =8
        - {{ pin_subpackage('openff-interchange-base', exact=True) }}
        - openff-toolkit >=0.18.0,<0.19
        - openff-packmol
        - pyedr

    test:
      requires:
        - python {{ python_min }}
        - packmol
      imports:
        - openff.interchange
      files:
        - test_stack_imports.py
      commands:
        - python test_stack_imports.py
        - which packmol  # doesn't seem to be a packmol --version or similar help command

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A project (and object) for storing, manipulating, and converting molecular mechanics data.
  dev_url: https://github.com/openforcefield/openff-interchange

extra:
  feedstock-name: openff-interchange
  recipe-maintainers:
    - mattwthompson
    - j-wags
